# Generated by Django 6.0.4 on 2026-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donationrequest_member_first_name_alter_member_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
