# Generated by Django 6.0.4 on 2026-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Membership Window',
                'verbose_name_plural': 'Membership Windows',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(default='/', max_length=500)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=20, unique=True)),
                ('ticket_tier', models.CharField(max_length=50)),
                ('ticket_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('proof_uploaded', 'Proof Uploaded'), ('approved', 'Approved'), ('awaiting_address', 'Awaiting Address'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='pending_payment', max_length=30)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='ticket_proofs/')),
                ('shipping_address', models.TextField(blank=True)),
                ('address_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='approval_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_proofs/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tier',
            field=models.CharField(default='Back Road Member', max_length=50),
        ),
    ]
