# Generated by Django 6.0.4 on 2026-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donationrequest_proof_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipWindow',
        ),
    ]
